// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0WfcM-C3QH9VfF4034hKXCdP-R01CkJc',
    appId: '1:638699514457:android:c876b2c65ea0cd0b9adf48',
    messagingSenderId: '638699514457',
    projectId: 'flutter-test-2-b1504',
    databaseURL: 'https://flutter-test-2-b1504-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-2-b1504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeYApbMKzKA_LQSJq0PWwwR3uYdbiGjbY',
    appId: '1:638699514457:ios:dd5543c9a616b50c9adf48',
    messagingSenderId: '638699514457',
    projectId: 'flutter-test-2-b1504',
    databaseURL: 'https://flutter-test-2-b1504-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-2-b1504.appspot.com',
    iosBundleId: 'com.example.monivalinta',
  );
}
